module Utilities
  module EnumHelper
    # @param [BaseModel] model class
    # @param [Symbol] attribute
    # @param [nil|String] variant
    def enum_collection: (untyped model, untyped attribute, ?untyped? variant) -> untyped

    # @param [BaseModel] model class
    # @param [Symbol] attribute
    # @param [Symbol|nil] value
    # @param [nil|String] variant
    def enum_translation: (untyped model, untyped attribute, untyped value, ?untyped? variant) -> ("" | untyped)
  end
end
