module Utilities::TemplateHelper

  interface _ToPartialPathDirect
    def to_partial_path: () -> String
  end

  interface _ToPartialPath
    def _to_partial_path: () -> String
  end

  def find_template_with_fallbacks: ((_ToPartialPath | _ToPartialPathDirect) obj, Symbol field, String base_path, String generic_field) -> ActionView::Template
end
