from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
    "echo '{{version}}' > lib/base_editing_bootstrap/VERSION",
    "docker compose run app bundle"
]
post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "docker compose run app gem build base_editing_bootstrap.gemspec",
    "docker compose run app gem push base_editing_bootstrap-{{version}}.gem"
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
