services:
  app:
    command: /app/spec/dummy/bin/dev
    build:
      context: .
    user: ${CMPS_UID_GID}
    volumes:
      - '.:/app'
      - 'bundle:/bundle'
      - '~/.gitconfig:/home/nobody/.gitconfig'
      - '~/.gnupg:/home/nobody/.gnupg'
    environment:
      RAILS_ENV: development
    ports:
      - 3000:3000

volumes:
  bundle: