module BaseEditingBootstrap::Searches
  class Field

    attr_reader search_base: Base

    attr_reader name: Symbol

    def initialize: (Base search_base, Symbol name) -> void

    def to_partial_path: () -> "search_field"

    def label: () -> String
  end
end
