module BaseEditingBootstrap
  interface _BaseModel

    def option_label: () -> String?

    def ransackable_attributes: (Object?) -> Object?

    def ransackable_associations: (Object?) -> [String]

    def read_attribute:(Symbol) -> untyped

    alias [] read_attribute

  end
end
